"use client"

import { useEffect, useState } from "react"
import { Database, Eye, FileSpreadsheet, Link2, SlidersHorizontal, Upload } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import type { SheetConnection } from "@/components/procurement/procurement-ui-types"
import type { ProcurementWorkspace, WorkspaceSettings } from "@/lib/procurement-types"

export function ProcurementSettings({ workspace, setWorkspace, sheetConnection, pageSize, setPageSize, exportXlsx, exportJson, openReport, importXlsx }: { workspace: ProcurementWorkspace; setWorkspace: React.Dispatch<React.SetStateAction<ProcurementWorkspace>>; sheetConnection: SheetConnection; pageSize: number; setPageSize: (size: number) => void; exportXlsx: () => void; exportJson: () => void; openReport: () => void; importXlsx: () => void }) {
  const updateSetting = <K extends keyof WorkspaceSettings>(key: K, value: WorkspaceSettings[K]) => setWorkspace((current) => ({ ...current, settings: { ...current.settings, [key]: value } }))
  return <div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-2">
    <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 font-display text-lg"><SlidersHorizontal className="text-[#2075b8]" />Pengaturan Umum</CardTitle><CardDescription>Preferensi tampilan aplikasi tersimpan pada browser ini.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Baris tabel default<Select value={String(pageSize)} onValueChange={(value) => { const size = Number(value) as 10 | 25 | 50 | 100; setPageSize(size); updateSetting("defaultPageSize", size) }}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{[10, 25, 50, 100].map((size) => <SelectItem key={size} value={String(size)}>{size} baris</SelectItem>)}</SelectContent></Select></label><label className="space-y-2 text-sm font-medium">Refresh data otomatis<Select value={String(workspace.settings.autoRefreshSeconds ?? 30)} onValueChange={(value) => updateSetting("autoRefreshSeconds", Number(value) as WorkspaceSettings["autoRefreshSeconds"])}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">Nonaktif</SelectItem><SelectItem value="30">30 detik</SelectItem><SelectItem value="60">1 menit</SelectItem><SelectItem value="120">2 menit</SelectItem></SelectContent></Select></label></CardContent></Card>
    <Card className="border-emerald-200 bg-gradient-to-br from-white to-emerald-50/60 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 font-display text-lg"><Link2 className="text-emerald-600" />Master Database</CardTitle><CardDescription>Pengadaan, requester, dan vendor tersinkron otomatis melalui Apps Script.</CardDescription></CardHeader><CardContent>{sheetConnection ? <div className="rounded-xl border border-emerald-200 bg-white p-4 text-sm"><p className="break-words font-semibold text-emerald-800">Terhubung · {sheetConnection.title}</p><p className="mt-1 text-slate-500">Sinkron terakhir {new Date(sheetConnection.lastSyncedAt).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}.</p></div> : <p className="text-sm text-slate-500">Menghubungkan backend…</p>}</CardContent></Card>
    <Card className="border-slate-200 shadow-sm lg:col-span-2"><CardHeader><CardTitle className="font-display text-lg">Import, export & portability</CardTitle><CardDescription>Kelola sumber data dan keluaran workspace dari satu tempat.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button variant="outline" onClick={importXlsx}><Upload /> Import XLSX</Button><Button onClick={openReport}><FileSpreadsheet /> Buat laporan PDF/DOCX/XLSX</Button><Button variant="outline" onClick={exportXlsx}><FileSpreadsheet /> Export master XLSX</Button><Button variant="outline" onClick={exportJson}><Database /> Backup workspace JSON</Button></CardContent></Card>
    <AccessibilitySettings />
  </div>
}

function AccessibilitySettings() {
  const [largeText, setLargeText] = useState(() => typeof window !== "undefined" && window.localStorage.getItem("procurement-sheets-lab.large-text") === "true")
  const [highContrast, setHighContrast] = useState(() => typeof window !== "undefined" && window.localStorage.getItem("procurement-sheets-lab.high-contrast") === "true")
  const [reduceMotion, setReduceMotion] = useState(() => typeof window !== "undefined" && window.localStorage.getItem("procurement-sheets-lab.reduce-motion") === "true")
  useEffect(() => { document.documentElement.classList.toggle("large-text", largeText); window.localStorage.setItem("procurement-sheets-lab.large-text", String(largeText)) }, [largeText])
  useEffect(() => { document.documentElement.classList.toggle("high-contrast", highContrast); window.localStorage.setItem("procurement-sheets-lab.high-contrast", String(highContrast)) }, [highContrast])
  useEffect(() => { document.documentElement.classList.toggle("reduce-motion", reduceMotion); window.localStorage.setItem("procurement-sheets-lab.reduce-motion", String(reduceMotion)) }, [reduceMotion])
  const options = [{ label: "Teks lebih besar", detail: "Perbesar seluruh tampilan tanpa zoom browser.", value: largeText, set: setLargeText }, { label: "Kontras tinggi", detail: "Pertegas teks, border, dan fokus kontrol.", value: highContrast, set: setHighContrast }, { label: "Kurangi animasi", detail: "Matikan transisi dan animasi yang tidak diperlukan.", value: reduceMotion, set: setReduceMotion }]
  return <Card className="border-slate-200 shadow-sm lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 font-display text-lg"><Eye className="text-[#2075b8]" />Accessibility</CardTitle><CardDescription>Pengaturan tersimpan di browser ini.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{options.map((option) => <label key={option.label} className="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><span><strong className="text-sm text-slate-900">{option.label}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{option.detail}</span></span><Switch checked={option.value} onCheckedChange={option.set} /></label>)}</CardContent></Card>
}
