"use client"

import { ChevronRight, FileSpreadsheet, Sparkles } from "lucide-react"
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ProcurementTable } from "@/components/procurement/procurement-table"
import { calculateSlaMetrics } from "@/lib/procurement-sla"
import type { ProcurementRecord, ProcurementStatus } from "@/lib/procurement-types"

const compact = new Intl.NumberFormat("id-ID", { notation: "compact", maximumFractionDigits: 1 })
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value)

function MetricCard({ label, value, detail, accent }: { label: string; value: string; detail: string; accent: string }) {
  return <Card className="relative min-h-28 overflow-hidden border-slate-200/80 py-3 shadow-sm"><div className={`absolute inset-x-0 top-0 h-1 ${accent}`} /><CardHeader className="gap-1 px-4"><CardDescription className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500">{label}</CardDescription><CardTitle className="font-display text-xl tracking-tight text-slate-950">{value}</CardTitle></CardHeader><CardContent className="px-4 text-xs text-slate-500">{detail}</CardContent></Card>
}

function DatabaseInsights({ monthlyFinancials, topVendors, topDivisions, savingsRate }: { monthlyFinancials: { month: string; expense: number; efficiency: number }[]; topVendors: { name: string; amount: number }[]; topDivisions: { name: string; amount: number }[]; savingsRate: number }) {
  const ranking = (title: string, data: { name: string; amount: number }[], color: string) => <Card className="border-slate-200/80 shadow-sm"><CardHeader><CardTitle className="font-display text-lg">{title}</CardTitle><CardDescription>Amount PO incl. PPN (IDR)</CardDescription></CardHeader><CardContent className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: 30, right: 24 }}><XAxis type="number" tickFormatter={(value) => compact.format(Number(value))} fontSize={10} /><YAxis dataKey="name" type="category" width={125} tick={{ fontSize: 10 }} /><Tooltip formatter={(value) => money(Number(value))} /><Bar dataKey="amount" name="Amount PO" fill={color} radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></CardContent></Card>
  return <section className="grid gap-5 xl:grid-cols-2"><Card className="border-slate-200/80 shadow-sm xl:col-span-2"><CardHeader><CardTitle className="font-display text-lg">Amount PO vs Efficiency</CardTitle><CardDescription>Tren bulanan IDR · savings {savingsRate.toFixed(1)}%</CardDescription></CardHeader><CardContent className="h-[280px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyFinancials}><CartesianGrid vertical={false} stroke="#dce8f3" /><XAxis dataKey="month" fontSize={11} /><YAxis tickFormatter={(value) => compact.format(Number(value))} width={58} fontSize={10} /><Tooltip formatter={(value) => money(Number(value))} /><Line type="monotone" dataKey="expense" name="Amount PO" stroke="#2075b8" strokeWidth={3} /><Line type="monotone" dataKey="efficiency" name="Efficiency" stroke="#73d94b" strokeWidth={3} /></LineChart></ResponsiveContainer></CardContent></Card>{ranking("Top 5 Spended Vendor", topVendors, "#2075b8")}{ranking("Top 5 Spender Divisi", topDivisions, "#082f63")}</section>
}

export function ProcurementDashboard({ year, years, setYear, requestRecords, statusData, monthlyData, expenseDisplay, efficiencyDisplay, goMaster, openReport }: { year: number; years: number[]; setYear: (year: number) => void; requestRecords: ProcurementRecord[]; statusData: { status: ProcurementStatus; value: number }[]; monthlyData: { month: string; total: number }[]; expenseDisplay: string; efficiencyDisplay: string; goMaster: () => void; openReport: () => void }) {
  const colors = ["#9be477", "#73d94b", "#2075b8", "#082f63", "#5a7898"]
  const idrRecords = requestRecords.filter((record) => record.currency === "IDR")
  const monthlyFinancials = monthlyData.map((item, index) => ({ ...item, expense: idrRecords.filter((record) => Number(record.requestDate.slice(5, 7)) === index + 1).reduce((sum, record) => sum + record.poAmountIncl, 0), efficiency: idrRecords.filter((record) => Number(record.requestDate.slice(5, 7)) === index + 1).reduce((sum, record) => sum + record.efficiency, 0) }))
  const topBy = (key: "selectedVendor" | "division") => Object.entries(idrRecords.reduce<Record<string, number>>((totals, record) => { const name = record[key]?.trim(); if (name) totals[name] = (totals[name] ?? 0) + record.poAmountIncl; return totals }, {})).map(([name, amount]) => ({ name, amount })).sort((a, b) => b.amount - a.amount).slice(0, 5).reverse()
  const totalIdrExpense = idrRecords.reduce((sum, record) => sum + record.poAmountIncl, 0)
  const totalIdrEfficiency = idrRecords.reduce((sum, record) => sum + record.efficiency, 0)
  const savingsRate = totalIdrExpense + totalIdrEfficiency ? totalIdrEfficiency / (totalIdrExpense + totalIdrEfficiency) * 100 : 0
  const slaMetrics = calculateSlaMetrics(requestRecords)

  return <div className="mx-auto flex max-w-[1500px] flex-col gap-4 [&_.h-\[290px\]]:h-[220px]">
    <section className="flex flex-col justify-between gap-4 rounded-2xl border border-blue-100 bg-white px-5 py-4 shadow-sm sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-sm font-semibold text-[#082f63]"><Sparkles className="size-4 text-[#73d94b]" /> Snapshot operasional</div><p className="mt-1 text-sm text-slate-500">Ringkasan performa procurement berdasarkan data yang tersedia.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Select value={String(year)} onValueChange={(value) => setYear(Number(value))}><SelectTrigger className="w-full min-w-40 border-blue-100 bg-blue-50/60 sm:w-44"><SelectValue /></SelectTrigger><SelectContent>{years.map((value) => <SelectItem key={value} value={String(value)}>Tahun {value}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={openReport}><FileSpreadsheet /> Export Laporan</Button></div></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total Pengadaan" value={String(requestRecords.length)} detail="Semua entry pada tahun request" accent="bg-[#082f63]" /><MetricCard label="Expense" value={expenseDisplay} detail="Total Amount PO incl. PPN" accent="bg-[#2075b8]" /><MetricCard label="Efficiency" value={efficiencyDisplay} detail="Total efficiency incl. PPN" accent="bg-[#73d94b]" /><MetricCard label="Saving" value={`${savingsRate.toFixed(2)}%`} detail="Efficiency ÷ (Expense + Efficiency)" accent="bg-emerald-500" /></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{slaMetrics.map((metric) => <Card key={metric.key} className="border-slate-200/80 shadow-sm"><CardHeader className="pb-2"><CardDescription className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[#2075b8]">{metric.label}</CardDescription><CardTitle className="font-display text-2xl text-[#082f63]">{metric.averageDays === null ? "—" : `${metric.averageDays.toFixed(1)} hari`}</CardTitle></CardHeader><CardContent className="space-y-2"><p className="text-xs text-slate-500">{metric.description} · hari kerja</p><div className="flex flex-wrap gap-x-3 gap-y-1 text-xs"><span className="font-semibold text-emerald-700">{metric.calculable} pengadaan selesai dihitung</span><span className="text-amber-700">{metric.unavailable} data tanggal belum lengkap</span></div></CardContent></Card>)}</section>
    <div className="[&>section>div]:min-h-56 [&>section>div]:min-w-72 [&>section>div]:resize [&>section>div]:overflow-auto"><DatabaseInsights monthlyFinancials={monthlyFinancials} topVendors={topBy("selectedVendor")} topDivisions={topBy("division")} savingsRate={savingsRate} /></div>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><Card className="border-slate-200/80 shadow-sm"><CardHeader className="border-b border-slate-100"><CardTitle className="font-display text-lg">Pengadaan per bulan</CardTitle><CardDescription>Tanggal request selama {year}</CardDescription></CardHeader><CardContent className="h-[290px] pt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyData} margin={{ left: -22, right: 8 }}><CartesianGrid vertical={false} stroke="#dce8f3" /><XAxis dataKey="month" tickLine={false} axisLine={false} fontSize={12} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={12} /><Tooltip cursor={{ fill: "#eef9e9" }} contentStyle={{ borderRadius: 12, borderColor: "#cfe0ef" }} /><Bar dataKey="total" name="Pengadaan" fill="#73d94b" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card><Card className="border-slate-200/80 shadow-sm"><CardHeader className="border-b border-slate-100"><CardTitle className="font-display text-lg">Komposisi status</CardTitle><CardDescription>{requestRecords.length} pengadaan pada {year}</CardDescription></CardHeader><CardContent className="grid min-h-[290px] grid-cols-[1.1fr_.9fr] items-center gap-2 pt-4"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="status" innerRadius={52} outerRadius={80} paddingAngle={3}>{colors.map((color) => <Cell key={color} fill={color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="space-y-2.5">{statusData.map((item, index) => <div key={item.status} className="flex items-center justify-between gap-4 text-sm"><span className="flex items-center gap-2 text-slate-600"><span className="size-2.5 rounded-full" style={{ background: colors[index] }} />{item.status}</span><strong className="font-display text-[#082f63]">{item.value}</strong></div>)}</div></CardContent></Card></section>
    <Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex-row items-center justify-between border-b border-slate-100"><div><CardTitle className="font-display text-lg">Pengadaan terbaru</CardTitle><CardDescription>Nomor baru tetap menyimpan Request ID asli.</CardDescription></div><Button variant="ghost" onClick={goMaster}>Lihat master <ChevronRight /></Button></CardHeader><CardContent className="px-0"><ProcurementTable records={requestRecords.slice(-6).reverse()} /></CardContent></Card>
  </div>
}
